#!/usr/bin/env bash

if
  [[ -s "/home/junko/.rvm/gems/ruby-2.1.2@railstutorial_rails_4_0/environment" ]]
then
  source "/home/junko/.rvm/gems/ruby-2.1.2@railstutorial_rails_4_0/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/junko/.rvm/gems/ruby-2.1.2@railstutorial_rails_4_0/environment'" >&2
  exit 1
fi
